site_name: TestLemon Documentation
site_url: https://docs.testlemon.com/
theme:
  name: readthedocs
extra_css: [css/extra.css]
nav:
  - Platform Configuration:
    - Home: index.md
  - Learning Center:
    - Use Testlemon to Test API: use-testlemon-to-test-api.md
  - References:
    - Examples: 'https://github.com/itbusina/testlemon-docs/tree/main/examples'
    - Portal: 'https://app.testlemon.com/'
    - Contact Us: 'https://testlemon.com/index.html#contact'
  - Privacy Policy: privacy-policy.md
  - Terms of Use: terms-of-use.md
