site_name: TestLemon Documentation
site_url: https://docs.testlemon.com/
site_description: 'Optimize your workflows with our powerful Web API Testing and Monitoring Tool. Automate testing, monitor performance, and ensure seamless API functionality with ease.'
theme:
  name: readthedocs
extra_css: [css/extra.css]
nav:
  - Platform Configuration:
    - Home: index.md
  - Learning Center:
    - Rest API: rest-api.md
    # - API Testing: api-testing.md
    - AI Augmented Testing: ai-augmented-testing.md
    - How to test API with Testlemon: how-to-test-api-with-testlemon.md
    # - Test end-to-end API workflows in Testlemon: test-end-to-end-api-workflows-in-testlemon.md
  - References:
    - Examples: 'https://github.com/itbusina/testlemon-docs/tree/main/examples'
    - Portal: 'https://app.testlemon.com/'
    - Contact Us: 'https://testlemon.com/index.html#contact'
  - Terms:
    - Privacy Policy: privacy-policy.md
    - Terms of Use: terms-of-use.md