site_name: TestLemon Documentation
site_url: https://docs.testlemon.com/
site_meta:
  description: "Test API, automate API testing, and monitor website uptime and domain configuration with our AI-augmented testing tool. Ensure seamless functionality with website monitoring, domain monitoring, site check, DMARC, DNS checks, and more. Streamline test automation and enhance API reliability."
  keywords: "api testing, site monitoring, test automation, dmarc, dkim, dns, test SSL, check TLS, test REST API, domain check, monitor website, uptime monitoring"
  author: "Kiryl Bahdanovich | CEO in itbusina.com | Founder of testlemon.com"
theme:
  name: readthedocs
extra_css: [css/extra.css]
nav:
  - Platform Configuration:
    - Home: index.md
  - Learning Center:
    - Rest API: rest-api.md
    - API Testing: api-testing.md
    - AI Augmented Testing: ai-augmented-testing.md
    - How to test API with Testlemon: how-to-test-api-with-testlemon.md
    # - Test end-to-end API workflows in Testlemon: test-end-to-end-api-workflows-in-testlemon.md
  - References:
    - Examples: 'https://github.com/itbusina/testlemon-docs/tree/main/examples'
    - Portal: 'https://app.testlemon.com/'
    - Contact Us: 'https://testlemon.com/index.html#contact'
  - Terms:
    - Privacy Policy: privacy-policy.md
    - Terms of Use: terms-of-use.md