name: XRay automatic tests provisioning

on:
  #push:
  #  paths:
  #    - 'src/api/**'
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        TEST_RESULTS=''
        docker run itbusina/testlemon:latest -c "$(<./examples/xray/auto-xray-provisioning.yaml)" -o -f xray >> $TEST_RESULTS
        echo TEST_RESULTS
        