name: XRay automatic tests provisioning

on:
  #push:
  #  paths:
  #    - 'src/api/**'
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        docker run --name testlemon --rm itbusina/testlemon:latest -c "$(<./examples/xray/auto-xray-provisioning.yaml)" -o output.json -f xray
        docker cp testlemon:/app/output.json output.json
        docker container prune
        TEST_RESULTS=$(<output.json)
        echo $TEST_RESULTS
        